# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [22]:
import numpy as np

#### 2. Print your NumPy version.

In [23]:
numpy.__version__

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [36]:
a = np.random.random((2,3,5))                    # genera randoms amb números decimals
print(a)

[[[0.69083496 0.02560382 0.70449629 0.27204808 0.89369276]
  [0.66735749 0.83213206 0.38544333 0.83133579 0.19723793]
  [0.05302879 0.47042338 0.64428218 0.09913696 0.31140729]]

 [[0.06575477 0.01316235 0.60905034 0.67265681 0.64957295]
  [0.75905084 0.54533548 0.30325561 0.15236493 0.42095301]
  [0.89243808 0.42893707 0.30304129 0.62429218 0.21653129]]]


In [34]:
b = np.random.rand(2,3,5)                        # genera randoms amb números decimals (del 0 a l'1)
print(b)

[[[0.83756324 0.34895723 0.33554263 0.56542862 0.18209228]
  [0.18278318 0.47387987 0.16533874 0.07073192 0.89611192]
  [0.92468927 0.71544696 0.02055313 0.27231262 0.57084719]]

 [[0.58607436 0.58866329 0.03514279 0.29042021 0.08944747]
  [0.829362   0.65498332 0.95169749 0.15864032 0.69353865]
  [0.89659241 0.73437086 0.05406935 0.40787647 0.53447742]]]


In [39]:
c = np.random.randint(0,10, size=(2,3,5))        # genera randoms amb integers
print(c)

[[[7 0 4 1 2]
  [3 2 8 5 9]
  [6 2 3 8 9]]

 [[3 4 1 7 7]
  [7 8 0 3 2]
  [2 2 2 1 0]]]


#### 4. Print *a*.


In [40]:
print(a)

[[[0.69083496 0.02560382 0.70449629 0.27204808 0.89369276]
  [0.66735749 0.83213206 0.38544333 0.83133579 0.19723793]
  [0.05302879 0.47042338 0.64428218 0.09913696 0.31140729]]

 [[0.06575477 0.01316235 0.60905034 0.67265681 0.64957295]
  [0.75905084 0.54533548 0.30325561 0.15236493 0.42095301]
  [0.89243808 0.42893707 0.30304129 0.62429218 0.21653129]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [43]:
b = np.ones((5,2,3), dtype='int32')

#### 6. Print *b*.


In [44]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [46]:
a.size == b.size    #tenen a i b el mateix número d'elements?

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [48]:
a+b
#No, because they don't have the same shape. 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [51]:
c = b.reshape(a.shape)
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [53]:
d = a+c          #funciona per què ara tenen la mateixa shape.
print(d)

[[[1.69083496 1.02560382 1.70449629 1.27204808 1.89369276]
  [1.66735749 1.83213206 1.38544333 1.83133579 1.19723793]
  [1.05302879 1.47042338 1.64428218 1.09913696 1.31140729]]

 [[1.06575477 1.01316235 1.60905034 1.67265681 1.64957295]
  [1.75905084 1.54533548 1.30325561 1.15236493 1.42095301]
  [1.89243808 1.42893707 1.30304129 1.62429218 1.21653129]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [61]:
print(a)
#print(d)
print(a+d)

[[[0.69083496 0.02560382 0.70449629 0.27204808 0.89369276]
  [0.66735749 0.83213206 0.38544333 0.83133579 0.19723793]
  [0.05302879 0.47042338 0.64428218 0.09913696 0.31140729]]

 [[0.06575477 0.01316235 0.60905034 0.67265681 0.64957295]
  [0.75905084 0.54533548 0.30325561 0.15236493 0.42095301]
  [0.89243808 0.42893707 0.30304129 0.62429218 0.21653129]]]
[[[2.38166992 1.05120763 2.40899258 1.54409616 2.78738552]
  [2.33471497 2.66426413 1.77088665 2.66267158 1.39447586]
  [1.10605758 1.94084675 2.28856436 1.19827391 1.62281459]]

 [[1.13150953 1.0263247  2.21810068 2.34531361 2.29914591]
  [2.51810167 2.09067097 1.60651122 1.30472985 1.84190603]
  [2.78487616 1.85787413 1.60608259 2.24858436 1.43306257]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [59]:
e = a*c    #
print(e)

[[[0.69083496 0.02560382 0.70449629 0.27204808 0.89369276]
  [0.66735749 0.83213206 0.38544333 0.83133579 0.19723793]
  [0.05302879 0.47042338 0.64428218 0.09913696 0.31140729]]

 [[0.06575477 0.01316235 0.60905034 0.67265681 0.64957295]
  [0.75905084 0.54533548 0.30325561 0.15236493 0.42095301]
  [0.89243808 0.42893707 0.30304129 0.62429218 0.21653129]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
#Yes, as you've basically multiplied a by 1.

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [64]:
d_max = np.max(d)
print(d_max)
d_min = np.min(d)
print(d_min)
d_mean = np.mean(d)
print(d_mean)

1.8936927580890426
1.0131623511341554
1.4578286028671932


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [70]:
f = np.empty(d.shape)
print(f)

[[[0.69083496 0.02560382 0.70449629 0.27204808 0.89369276]
  [0.66735749 0.83213206 0.38544333 0.83133579 0.19723793]
  [0.05302879 0.47042338 0.64428218 0.09913696 0.31140729]]

 [[0.06575477 0.01316235 0.60905034 0.67265681 0.64957295]
  [0.75905084 0.54533548 0.30325561 0.15236493 0.42095301]
  [0.89243808 0.42893707 0.30304129 0.62429218 0.21653129]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [1]:
for i in d:
    if i > d_min and < d_mean:
        return
for i in d:
    if i > d_mean and < d_max:
        i = 75
        

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [71]:
print(d)
print(f)

[[[1.69083496 1.02560382 1.70449629 1.27204808 1.89369276]
  [1.66735749 1.83213206 1.38544333 1.83133579 1.19723793]
  [1.05302879 1.47042338 1.64428218 1.09913696 1.31140729]]

 [[1.06575477 1.01316235 1.60905034 1.67265681 1.64957295]
  [1.75905084 1.54533548 1.30325561 1.15236493 1.42095301]
  [1.89243808 1.42893707 1.30304129 1.62429218 1.21653129]]]
[[[0.69083496 0.02560382 0.70449629 0.27204808 0.89369276]
  [0.66735749 0.83213206 0.38544333 0.83133579 0.19723793]
  [0.05302879 0.47042338 0.64428218 0.09913696 0.31140729]]

 [[0.06575477 0.01316235 0.60905034 0.67265681 0.64957295]
  [0.75905084 0.54533548 0.30325561 0.15236493 0.42095301]
  [0.89243808 0.42893707 0.30304129 0.62429218 0.21653129]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here