# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [4]:
import numpy as np

#### 2. Print your NumPy version.

In [5]:
np.version.version

'1.19.0'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [36]:
# Method 1 (np.random.random)

In [35]:
# Method 2 (np.random.normal(n, n, (n, n))

In [37]:
# Method 3 (np.random.randint(n, n (n, n))

#### 4. Print *a*.


In [38]:
a = np.random.random((2, 3, 5))
a

array([[[0.02011868, 0.12104898, 0.4808412 , 0.80009768, 0.04007009],
        [0.88306401, 0.81676226, 0.32661953, 0.76857566, 0.90724404],
        [0.3201298 , 0.73577762, 0.26913931, 0.79353375, 0.71007267]],

       [[0.78692828, 0.60991198, 0.98191047, 0.86582418, 0.09728863],
        [0.6303495 , 0.93655342, 0.38905677, 0.80662292, 0.79606216],
        [0.00226887, 0.36288249, 0.45137162, 0.00933617, 0.43785426]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [42]:
b = np.ones((5, 2, 3))

#### 6. Print *b*.


In [43]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [44]:
print(a.size)
print(b.size)

# Yes, they both have the same size

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [47]:
# No, because the shape is different

print(a.shape)
print(b.shape)

(2, 3, 5)
(5, 2, 3)


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [65]:
c = b.reshape(2, 3, 5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [66]:
d = np.add(a, c)
d

# It works because both a & c are 2x3x5

array([[[1.02011868, 1.12104898, 1.4808412 , 1.80009768, 1.04007009],
        [1.88306401, 1.81676226, 1.32661953, 1.76857566, 1.90724404],
        [1.3201298 , 1.73577762, 1.26913931, 1.79353375, 1.71007267]],

       [[1.78692828, 1.60991198, 1.98191047, 1.86582418, 1.09728863],
        [1.6303495 , 1.93655342, 1.38905677, 1.80662292, 1.79606216],
        [1.00226887, 1.36288249, 1.45137162, 1.00933617, 1.43785426]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [67]:
print(a)
print(d)

# When we added c to a, the integer 1 in c was summed to the 0s in a

[[[0.02011868 0.12104898 0.4808412  0.80009768 0.04007009]
  [0.88306401 0.81676226 0.32661953 0.76857566 0.90724404]
  [0.3201298  0.73577762 0.26913931 0.79353375 0.71007267]]

 [[0.78692828 0.60991198 0.98191047 0.86582418 0.09728863]
  [0.6303495  0.93655342 0.38905677 0.80662292 0.79606216]
  [0.00226887 0.36288249 0.45137162 0.00933617 0.43785426]]]
[[[1.02011868 1.12104898 1.4808412  1.80009768 1.04007009]
  [1.88306401 1.81676226 1.32661953 1.76857566 1.90724404]
  [1.3201298  1.73577762 1.26913931 1.79353375 1.71007267]]

 [[1.78692828 1.60991198 1.98191047 1.86582418 1.09728863]
  [1.6303495  1.93655342 1.38905677 1.80662292 1.79606216]
  [1.00226887 1.36288249 1.45137162 1.00933617 1.43785426]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [72]:
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [73]:
print(e)

# Yes, equal, because a was multiplied by c, which is 1, so the result is the same

[[[0.02011868 0.12104898 0.4808412  0.80009768 0.04007009]
  [0.88306401 0.81676226 0.32661953 0.76857566 0.90724404]
  [0.3201298  0.73577762 0.26913931 0.79353375 0.71007267]]

 [[0.78692828 0.60991198 0.98191047 0.86582418 0.09728863]
  [0.6303495  0.93655342 0.38905677 0.80662292 0.79606216]
  [0.00226887 0.36288249 0.45137162 0.00933617 0.43785426]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [87]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d_max)
print(d_min)
print(d_mean)

1.9819104695859213
1.002268867795839
1.538577232690283


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [79]:
f = np.empty((2, 3, 5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [85]:
for i in d:
    if i > (d_min) & i < (d_mean):
        print(d)
        
# At this very moment, I'm unable to figure out. I will come back soon!

TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [ ]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here