# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1

# random value
a = np.random.random((2,3,5))

In [4]:
# Method 2

# Random values from 0 to 1
a = np.random.rand(2,3,5)

In [5]:
# Method 3

# random integer values form 0 to 100
a = np.random.randint(0,101,(2,3,5))

#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[ 88  71 100  48   4]
  [ 39  49  13  14  45]
  [ 66  66  44  51  78]]

 [[ 41  87  89  66  27]
  [ 54  36  91   7  57]
  [ 76  83 100  80  13]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here

b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
if a.shape == b.shape:
    print('Both arrays have the same size')
else:
    print(f'Arrays a and b do not have the same size: a has size {a.shape} and b, {b.shape}')

Arrays a and b do not have the same size: a has size (2, 3, 5) and b, (5, 2, 3)


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
print('not possible to add a and b because their size is different')

not possible to add a and b because their size is different


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [13]:
# your code here

c = b.reshape((2,3,5))

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [15]:
# your code/answer here
d = a + c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [21]:
# your code/answer here

print(f'a ={a}\n\n')

print(f'd ={d}\n\n')

print('The difference between a and d is 1, because we have added to a an array of ones')

a =[[[ 88  71 100  48   4]
  [ 39  49  13  14  45]
  [ 66  66  44  51  78]]

 [[ 41  87  89  66  27]
  [ 54  36  91   7  57]
  [ 76  83 100  80  13]]]


d =[[[ 89.  72. 101.  49.   5.]
  [ 40.  50.  14.  15.  46.]
  [ 67.  67.  45.  52.  79.]]

 [[ 42.  88.  90.  67.  28.]
  [ 55.  37.  92.   8.  58.]
  [ 77.  84. 101.  81.  14.]]]


The difference between a and d is 1, because we have added to a an array of ones


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [22]:
# your code here

e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [29]:
# your code/answer here
if e.all() == a.all():
    print('a is equal to e beause we have multiply by c which is an array that only contains ones')

a is equal to e beause we have multiply by c which is an array that only contains ones


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [30]:
# your code here
d_max = d.max()
print(f'The max of d is {d_max}')

d_min = d.min()
print(f'The min of d is {d_min}')
      
d_mean = d.mean()
print(f'The mean of d is {d_mean}')

The max of d is 101.0
The min of d is 5.0
The mean of d is 57.1


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [35]:
# your code here
f = np.empty(d.shape)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [57]:
# your code here
i = 0
j = 0
k = 0

for depth in d:
    for row in depth:
        for num in row:
            if num > d_min and num < d_mean:
                f[i][j][k] = 25
            elif num > d_mean and num < d_max:
                f[i][j][k] = 75
            elif num == d_mean:
                f[i][j][k] = 50
            elif num < d_min:
                f[i][j][k] = 0
            else:
                f[i][j][k] = 100
            k += 1
        j += 1
        k = 0
    i += 1
    j = 0
    k = 0
    

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [58]:
# your code here

print(f'd ={d}\n\n')

print(f'f ={f}')

d =[[[ 89.  72. 101.  49.   5.]
  [ 40.  50.  14.  15.  46.]
  [ 67.  67.  45.  52.  79.]]

 [[ 42.  88.  90.  67.  28.]
  [ 55.  37.  92.   8.  58.]
  [ 77.  84. 101.  81.  14.]]]


f =[[[ 75.  75. 100.  25. 100.]
  [ 25.  25.  25.  25.  25.]
  [ 75.  75.  25.  25.  75.]]

 [[ 25.  75.  75.  75.  25.]
  [ 25.  25.  75.  25.  75.]
  [ 75.  75. 100.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [64]:
# your code here
g = np.where((d > d_min) & (d < d_mean), 'B', 
             np.where((d > d_mean) & (d < d_max), 'D',
                      np.where((d == d_mean), 'C', 
                               np.where((d == d_min), 'A',
                                        np.where((d == d_max), 'E', 'Error')))))

print(g)

[[['D' 'D' 'E' 'B' 'A']
  ['B' 'B' 'B' 'B' 'B']
  ['D' 'D' 'B' 'B' 'D']]

 [['B' 'D' 'D' 'D' 'B']
  ['B' 'B' 'D' 'B' 'D']
  ['D' 'D' 'E' 'D' 'B']]]
