# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [110]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [111]:
# your code here
np.__version__

'1.21.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [112]:
# Method 1
a = np.random.randint(1,100,(2,3,5))

In [113]:
# Method 2
a = np.random.rand(2,3,5)

In [114]:
# Method 3
a = np.random.randn(2,3,5)

#### 4. Print *a*.


In [115]:
# your code here
print(a)

[[[ 0.40366472 -0.05918443  0.67748856  0.89129483  1.18652615]
  [ 1.510393   -1.01314854 -0.64781386  0.10512491 -0.16518378]
  [-0.50302129 -0.52500584  1.03720889 -0.05750656 -0.50983949]]

 [[ 1.03524344 -0.07785039 -0.52831281 -0.53007634  0.58927694]
  [-0.65930731  0.0949154  -1.26021852  0.16141724  0.44673383]
  [ 0.07636574 -0.84802007 -0.34575771  0.27483238 -0.98728331]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [116]:
# your code here
b = np.ones((5,2,3), dtype='int64')

#### 6. Print *b*.


In [117]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [118]:
# your code here
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [119]:
# your answer here
try:
    a + b
except ValueError:
    print('could not add a + b because arrays have to have same shape')

could not add a + b because arrays have to have same shape


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [120]:
# your code here

print('Initial b shape ', b.shape)
print('Initial a shape ',a.shape)

c = b.reshape((2,3,5)).copy()

print('New array c with shape: ', c.shape)

Initial b shape  (5, 2, 3)
Initial a shape  (2, 3, 5)
New array c with shape:  (2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [121]:
# your code/answer here
d = (a + c).copy()
print('now both arrays have the same shape so numpy adds member to member')

now both arrays have the same shape so numpy adds member to member


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [122]:
# your code/answer here
print(a)
print(d)

print('''
c is an array made of Ones, so adding them to a , made each value of d
increment one.
''')

[[[ 0.40366472 -0.05918443  0.67748856  0.89129483  1.18652615]
  [ 1.510393   -1.01314854 -0.64781386  0.10512491 -0.16518378]
  [-0.50302129 -0.52500584  1.03720889 -0.05750656 -0.50983949]]

 [[ 1.03524344 -0.07785039 -0.52831281 -0.53007634  0.58927694]
  [-0.65930731  0.0949154  -1.26021852  0.16141724  0.44673383]
  [ 0.07636574 -0.84802007 -0.34575771  0.27483238 -0.98728331]]]
[[[ 1.40366472  0.94081557  1.67748856  1.89129483  2.18652615]
  [ 2.510393   -0.01314854  0.35218614  1.10512491  0.83481622]
  [ 0.49697871  0.47499416  2.03720889  0.94249344  0.49016051]]

 [[ 2.03524344  0.92214961  0.47168719  0.46992366  1.58927694]
  [ 0.34069269  1.0949154  -0.26021852  1.16141724  1.44673383]
  [ 1.07636574  0.15197993  0.65424229  1.27483238  0.01271669]]]

c is an array made of Ones, so adding them to a , made each value of d
increment one.



#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [123]:
# your code here
e = (a * c).copy()

#### 13. Does *e* equal to *a*? Why or why not?


In [124]:
# your code/answer here
print(e == a)
print('''
Since c was an array of Ones, the values of e and c are the same 
''')


[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]

Since c was an array of Ones, the values of e and c are the same 



#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [125]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [126]:
# your code here
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [127]:
# your code here

# variables dim1,2,3 are positional
dim1 = -1

#loop dimension 1
for ele in d:
    dim1 += 1
    dim2 = -1
    #loop dimension 2
    for subele in ele:
        dim2 += 1
        dim3 = -1
        #loop dimension 3
        for subsubele in subele:
            dim3 += 1
            
            #check conditions and assign f based on positions dim1,2,3
            if subsubele > d_min and subsubele < d_mean:
                f[(dim1,dim2,dim3)] = 25
            elif subsubele > d_mean and subsubele < d_max:
                f[(dim1,dim2,dim3)] = 75
            elif subsubele == d_mean:
                f[(dim1,dim2,dim3)] = 50
            elif subsubele == d_max:
                f[(dim1,dim2,dim3)] = 100
            elif subsubele == d_min:
                f[(dim1,dim2,dim3)] = 0
                
 

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [128]:
# your code here
print(f)

[[[ 75.  25.  75.  75.  75.]
  [100.  25.  25.  75.  25.]
  [ 25.  25.  75.  25.  25.]]

 [[ 75.  25.  25.  25.  75.]
  [ 25.  75.   0.  75.  75.]
  [ 75.  25.  25.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [129]:
# your code here

# change type of array to python object
f = f.astype('object')

dim1 = -1
for ele in d:
    dim1 += 1
    dim2 = -1
    
    for subele in ele:
        dim2 += 1
        dim3 = -1
        for subsubele in subele:
            dim3 += 1
            if subsubele > d_min and subsubele < d_mean:
                f[(dim1,dim2,dim3)] = 'B'
            elif subsubele > d_mean and subsubele < d_max:
                f[(dim1,dim2,dim3)] = 'D'
            elif subsubele == d_mean:
                f[(dim1,dim2,dim3)] = 'C'
            elif subsubele == d_max:
                f[(dim1,dim2,dim3)] = 'E'
            elif subsubele == d_min:
                f[(dim1,dim2,dim3)] = 'A'

In [130]:
print(f)

[[['D' 'B' 'D' 'D' 'D']
  ['E' 'B' 'B' 'D' 'B']
  ['B' 'B' 'D' 'B' 'B']]

 [['D' 'B' 'B' 'B' 'D']
  ['B' 'D' 'A' 'D' 'D']
  ['D' 'B' 'B' 'D' 'B']]]
