# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
print (np.__version__)

1.19.0


In [4]:
#hay estas forma de tener la version, ¿cual seria la correcta?
np.version.version

'1.19.0'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
# Method 1
l=[[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]]

In [6]:
a=np.array(l)

In [7]:
a

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

In [8]:
# Method 2
arr2=np.random.randint(0,10,(2,3,5))

In [9]:
arr2

array([[[7, 9, 8, 2, 4],
        [8, 4, 0, 7, 0],
        [0, 3, 1, 6, 9]],

       [[5, 3, 6, 7, 9],
        [7, 7, 2, 6, 2],
        [1, 3, 5, 6, 4]]])

In [10]:
# Method 3
arr3=np.zeros((2,3,5))

In [11]:
arr3

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [12]:
arr4=np.full((2,3,5), 5)

In [13]:
arr4

array([[[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]],

       [[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]]])

#### 4. Print *a*.


In [14]:
# your code here
a

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [15]:
# your code here
b=a.reshape((5,2,3))

#### 6. Print *b*.


In [16]:
# your code here
b

array([[[1, 2, 3],
        [4, 5, 1]],

       [[2, 3, 4],
        [5, 1, 2]],

       [[3, 4, 5],
        [1, 2, 3]],

       [[4, 5, 1],
        [2, 3, 4]],

       [[5, 1, 2],
        [3, 4, 5]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [17]:
# your code here
a.itemsize==b.itemsize

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [18]:
# your answer here
#We can't coz they have diferent shapes

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [19]:
# your code here
c=b.reshape((2,3,5))

In [20]:
c

array([[[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]],

       [[1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [21]:
# your code/answer here
#we can add them as they have the same shape now
d=a+c

In [22]:
d

array([[[ 2,  4,  6,  8, 10],
        [ 2,  4,  6,  8, 10],
        [ 2,  4,  6,  8, 10]],

       [[ 2,  4,  6,  8, 10],
        [ 2,  4,  6,  8, 10],
        [ 2,  4,  6,  8, 10]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [23]:
# your code/answer here
#we see they have same shape, but diferent values->each value in b is the value*2 in a.
print(a)
print("\n")
print(d)

[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]]


[[[ 2  4  6  8 10]
  [ 2  4  6  8 10]
  [ 2  4  6  8 10]]

 [[ 2  4  6  8 10]
  [ 2  4  6  8 10]
  [ 2  4  6  8 10]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [24]:
# your code here
e=a*c

In [25]:
e

array([[[ 1,  4,  9, 16, 25],
        [ 1,  4,  9, 16, 25],
        [ 1,  4,  9, 16, 25]],

       [[ 1,  4,  9, 16, 25],
        [ 1,  4,  9, 16, 25],
        [ 1,  4,  9, 16, 25]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [26]:
# your code/answer here
#e !n a -> as we are now multiplying every nunber by themselves.

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [27]:
# your code here
d_max=d.max()
d_min=d.min()
d_mean=d.mean()

In [28]:
d_max

10

In [29]:
d_min

2

In [30]:
d_mean

6.0

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [42]:
# your code here
f=np.zeros((2,3,5))

In [43]:
print(f)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [44]:
print(d)

[[[ 2  4  6  8 10]
  [ 2  4  6  8 10]
  [ 2  4  6  8 10]]

 [[ 2  4  6  8 10]
  [ 2  4  6  8 10]
  [ 2  4  6  8 10]]]


In [45]:
for i in range(0, len(d)): 
    for subi in range(len(d[i])):
        for subi2 in range(len(d[i][subi])):
            if d[i][subi][subi2]<d_min and d[i][subi][subi2]<d_min:
                f[i][subi][subi2] = 25
            elif d[i][subi][subi2]<d_mean and d[i][subi][subi2]<d_max:
                f[i][subi][subi2] = 75
            elif d[i][subi][subi2]==d_mean:
                f[i][subi][subi2] = 50
            elif d[i][subi][subi2]==d_min:
                f[i][subi][subi2] = 0
            elif d[i][subi][subi2]==d_max:
                f[i][subi][subi2] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [46]:
# your code here
print(d)
print("\n")
print(f)

[[[ 2  4  6  8 10]
  [ 2  4  6  8 10]
  [ 2  4  6  8 10]]

 [[ 2  4  6  8 10]
  [ 2  4  6  8 10]
  [ 2  4  6  8 10]]]


[[[ 75.  75.  50.   0. 100.]
  [ 75.  75.  50.   0. 100.]
  [ 75.  75.  50.   0. 100.]]

 [[ 75.  75.  50.   0. 100.]
  [ 75.  75.  50.   0. 100.]
  [ 75.  75.  50.   0. 100.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [50]:
# your code here
#lo haría con np.where, pero no se como no usar Numpy aquí