# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here
np.__version__

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [52]:
# Method 1
a = np.random.randint(0, 100, size=(2, 3, 5))

In [51]:
# Method 2
a = np.random.randn(2, 3, 5)

In [29]:
# Method 3
a = np.random.rand(2, 3, 5)

array([[[0.18001635, 0.13407509, 0.54096759, 0.84997582, 0.35167002],
        [0.09200013, 0.97961894, 0.17998556, 0.96054005, 0.37327644],
        [0.66546648, 0.21900174, 0.01624266, 0.2968813 , 0.3467898 ]],

       [[0.43488631, 0.2246578 , 0.96876905, 0.31384036, 0.2273734 ],
        [0.80705995, 0.16266274, 0.44217497, 0.59942746, 0.53255604],
        [0.47714086, 0.74693635, 0.83696756, 0.94529042, 0.62397077]]])

#### 4. Print *a*.


In [53]:
# your code here
a

array([[[85, 58, 55, 80, 42],
        [24, 65, 73, 25, 56],
        [60, 74, 60, 93, 46]],

       [[17, 85, 62, 15, 47],
        [69, 15, 73, 37, 90],
        [10, 58, 84, 97, 30]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [56]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [57]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [58]:
# your code here
a.size

30

In [59]:
b.size

30

In [60]:
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [62]:
# your answer here
np.add(a,b)

#Different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [73]:
# your code here
c = b.reshape((2, 3, 5))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [74]:
# your code/answer here
d = np.add(a,c)
d

array([[[86., 59., 56., 81., 43.],
        [25., 66., 74., 26., 57.],
        [61., 75., 61., 94., 47.]],

       [[18., 86., 63., 16., 48.],
        [70., 16., 74., 38., 91.],
        [11., 59., 85., 98., 31.]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [75]:
# your code/answer here
a

array([[[85, 58, 55, 80, 42],
        [24, 65, 73, 25, 56],
        [60, 74, 60, 93, 46]],

       [[17, 85, 62, 15, 47],
        [69, 15, 73, 37, 90],
        [10, 58, 84, 97, 30]]])

In [76]:
d

array([[[86., 59., 56., 81., 43.],
        [25., 66., 74., 26., 57.],
        [61., 75., 61., 94., 47.]],

       [[18., 86., 63., 16., 48.],
        [70., 16., 74., 38., 91.],
        [11., 59., 85., 98., 31.]]])

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [78]:
# your code here

e = np.multiply(a,c)
e

array([[[85., 58., 55., 80., 42.],
        [24., 65., 73., 25., 56.],
        [60., 74., 60., 93., 46.]],

       [[17., 85., 62., 15., 47.],
        [69., 15., 73., 37., 90.],
        [10., 58., 84., 97., 30.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [80]:
# your code/answer here

e == a

#It a multiplication by 1's

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [83]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

d_max

98.0

In [84]:
d_min

11.0

In [85]:
d_mean

57.166666666666664

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [108]:
# your code here
f = np.empty((2, 3, 5))



In [109]:
f

array([[[75., 58., 55., 80., 42.],
        [25., 65., 73., 25., 56.],
        [75., 74., 60., 93., 46.]],

       [[25., 85., 62., 15., 47.],
        [75., 15., 73., 37., 90.],
        [ 0., 58., 84., 97., 30.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [111]:
# your code here
# Intento hacerlo con IF's pero no se como llegar a tanta profundida. 

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [112]:
# your code here
print(f)

[[[75. 58. 55. 80. 42.]
  [25. 65. 73. 25. 56.]
  [75. 74. 60. 93. 46.]]

 [[25. 85. 62. 15. 47.]
  [75. 15. 73. 37. 90.]
  [ 0. 58. 84. 97. 30.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [ ]:
# your code here