# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [5]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [6]:
# your code here
print(np.__version__)

1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [13]:
# Method 1
#We use Numpy randint() function when we need to create a NumPy array filled with random integer values.

a1 = np.random.randint(0, 10, (2,3,5))
print(a1)

[[[1 7 1 4 9]
  [8 2 4 2 4]
  [2 2 7 3 0]]

 [[2 4 9 0 0]
  [1 2 3 0 8]
  [3 3 0 5 6]]]


In [14]:
# Method 2
#We use Numpy randn() function when we want to create a NumPy array filled with floating-point random numbers that 
#are both positive and negative. 

a2 = np.random.randn(2,3,5)
print(a2)

[[[ 1.26480375 -0.30968727 -0.84635383 -0.46421771 -0.37041475]
  [ 0.88844598 -1.03859011  1.59506383  0.63522809 -0.23092231]
  [-1.96677367  1.39567062  0.68581893 -0.6448767   1.29406433]]

 [[ 0.40435895 -0.57366272 -0.52522218  0.36541989 -0.51910948]
  [-1.24597396  0.00306788 -0.71830112  1.17320242 -0.75711028]
  [ 0.64700983 -0.51438044  0.67249213 -0.56332109  0.21140048]]]


In [15]:
# Method 3
#Numpy rand() function is used when we want to create a NumPy array filled with random floating-point numbers that are
#only positive and in the range [0,1).

a3 = np.random.rand(2,3,5)
print(a3)

[[[0.68370936 0.49060042 0.62379407 0.25492778 0.96035199]
  [0.42063605 0.15123354 0.06222862 0.79610369 0.29698656]
  [0.61027312 0.38740701 0.53541041 0.72248413 0.93395782]]

 [[0.11714288 0.36119799 0.9386278  0.89992006 0.63344798]
  [0.54246021 0.43663203 0.47596062 0.60615055 0.63786784]
  [0.50937649 0.51232999 0.96992589 0.12243715 0.64822091]]]


#### 4. Print *a*.


In [54]:
# your code here
a = a3
print(a)

[[[0.68370936 0.49060042 0.62379407 0.25492778 0.96035199]
  [0.42063605 0.15123354 0.06222862 0.79610369 0.29698656]
  [0.61027312 0.38740701 0.53541041 0.72248413 0.93395782]]

 [[0.11714288 0.36119799 0.9386278  0.89992006 0.63344798]
  [0.54246021 0.43663203 0.47596062 0.60615055 0.63786784]
  [0.50937649 0.51232999 0.96992589 0.12243715 0.64822091]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [55]:
# your code here
b = np.ones((5, 2, 3), dtype=np.int64)

#### 6. Print *b*.


In [56]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [57]:
# your code here
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [66]:
# your answer here
np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [58]:
#To add two arrays together, we use the np.add(arr1,arr2) method. This method can be used only if the arrays have the 
#same shape. But the shapes of the arrays "a"and "b" are different.
np.shape(a) == np.shape(b)

False

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [60]:
# your code here
print(f'The shape of the array "a" is: {a.shape}')
print(f'While the shape of the array "b" is: {b.shape}')
c = b.reshape(2,3,5)
print(f'After reshaping the array "b" we get the new array "c" with the shape: {c.shape}')

The shape of the array "a" is: (2, 3, 5)
While the shape of the array "b" is: (5, 2, 3)
After reshaping the array "b" we get the new array "c" with the shape: (2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [61]:
# your code/answer here
d = np.add(a,c)

In [62]:
#It works now because the shapes of the arrays "a" and "c" are the same
np.shape(a) == np.shape(c)

True

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [63]:
# your code/answer here
print(f'The array a:\n\n {a}\n')

print(f'The array d:\n\n {d}\n')

#Both arrays are filled with the floating-point numbers. The elements of the array "d" are those from the array "a" 
#but incremented by 1

The array a:

 [[[0.68370936 0.49060042 0.62379407 0.25492778 0.96035199]
  [0.42063605 0.15123354 0.06222862 0.79610369 0.29698656]
  [0.61027312 0.38740701 0.53541041 0.72248413 0.93395782]]

 [[0.11714288 0.36119799 0.9386278  0.89992006 0.63344798]
  [0.54246021 0.43663203 0.47596062 0.60615055 0.63786784]
  [0.50937649 0.51232999 0.96992589 0.12243715 0.64822091]]]

The array d:

 [[[1.68370936 1.49060042 1.62379407 1.25492778 1.96035199]
  [1.42063605 1.15123354 1.06222862 1.79610369 1.29698656]
  [1.61027312 1.38740701 1.53541041 1.72248413 1.93395782]]

 [[1.11714288 1.36119799 1.9386278  1.89992006 1.63344798]
  [1.54246021 1.43663203 1.47596062 1.60615055 1.63786784]
  [1.50937649 1.51232999 1.96992589 1.12243715 1.64822091]]]



#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [64]:
# your code here
e = np.multiply(a, c)
print(e)

[[[0.68370936 0.49060042 0.62379407 0.25492778 0.96035199]
  [0.42063605 0.15123354 0.06222862 0.79610369 0.29698656]
  [0.61027312 0.38740701 0.53541041 0.72248413 0.93395782]]

 [[0.11714288 0.36119799 0.9386278  0.89992006 0.63344798]
  [0.54246021 0.43663203 0.47596062 0.60615055 0.63786784]
  [0.50937649 0.51232999 0.96992589 0.12243715 0.64822091]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [67]:
# your code/answer here
e == a
#"e" is equal to "a" as soon as the "c" is the array of Ones

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [74]:
# your code here
d_max = d.max()
print(f'The max value of "d" is: {d_max}')
d_min = d.min()
print(f'The min value of "d" is: {d_min}')
d_mean = d.mean()
print(f'The mean value of "d" is: {d_mean}')

The max value of "d" is: 1.969925886760931
The min value of "d" is: 1.062228624859444
The mean value of "d" is: 1.5447267659496946


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [95]:
# your code here
f = np.empty((2,3,5), dtype=np.float64)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [96]:
# your code here
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = 25
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] = 75
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 50
            elif d[i][j][k] == d_min:
                f[i][j][k] = 0
            elif d[i][j][k] == d_max:
                f[i][j][k] = 100         

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [97]:
# your code here
print(f'The array d:\n\n {d}\n')

print(f'The array f:\n\n {f}\n')

The array d:

 [[[1.68370936 1.49060042 1.62379407 1.25492778 1.96035199]
  [1.42063605 1.15123354 1.06222862 1.79610369 1.29698656]
  [1.61027312 1.38740701 1.53541041 1.72248413 1.93395782]]

 [[1.11714288 1.36119799 1.9386278  1.89992006 1.63344798]
  [1.54246021 1.43663203 1.47596062 1.60615055 1.63786784]
  [1.50937649 1.51232999 1.96992589 1.12243715 1.64822091]]]

The array f:

 [[[ 75.  25.  75.  25.  75.]
  [ 25.  25.   0.  75.  25.]
  [ 75.  25.  25.  75.  75.]]

 [[ 25.  25.  75.  75.  75.]
  [ 25.  25.  25.  75.  75.]
  [ 25.  25. 100.  25.  75.]]]



#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [98]:
# your code here
g = np.empty((2,3,5), dtype=str)

In [99]:
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                g[i][j][k] = 'B'
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                g[i][j][k] = 'D'
            elif d[i][j][k] == d_mean:
                g[i][j][k] = 'C'
            elif d[i][j][k] == d_min:
                g[i][j][k] = 'A'
            elif d[i][j][k] == d_max:
                g[i][j][k] = 'E'  
print(g)                

[[['D' 'B' 'D' 'B' 'D']
  ['B' 'B' 'A' 'D' 'B']
  ['D' 'B' 'B' 'D' 'D']]

 [['B' 'B' 'D' 'D' 'D']
  ['B' 'B' 'B' 'D' 'D']
  ['B' 'B' 'E' 'B' 'D']]]
