# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [108]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [109]:
# your code here
print(np.__version__)


1.19.0


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [110]:
# Method 1
a = np.random.random((2,3,5))


In [111]:
# Method 2
array= np.random.randint(0,10,(2,3,5))
array

array([[[9, 1, 5, 4, 2],
        [3, 5, 6, 7, 1],
        [6, 6, 9, 5, 2]],

       [[4, 4, 7, 7, 0],
        [8, 3, 8, 0, 3],
        [7, 8, 5, 8, 5]]])

In [112]:
# Method 3

#### 4. Print *a*.


In [113]:
# your code here
print(a)

[[[0.13569819 0.13513816 0.57969184 0.47125058 0.69520073]
  [0.70424357 0.67294378 0.99803467 0.17655615 0.3317925 ]
  [0.17505148 0.0780165  0.6511064  0.08144937 0.59447449]]

 [[0.91264682 0.33161921 0.17646838 0.81680065 0.93171856]
  [0.12086502 0.72219922 0.68680907 0.47124441 0.8869206 ]
  [0.28811097 0.91661677 0.97549623 0.17347029 0.61229793]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [114]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [115]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [116]:
# your code here
print(a.size)
print(b.size)

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [117]:
# your answer here
#It's not possible, because they have different shapes
np.add(a,b)


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [118]:
# your code here
c = b.reshape((2, 3, 5))



#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [119]:
# your code/answer here
d = np.add(a,c)
d
#Because they both have the same shape (2x3x5)

array([[[1.13569819, 1.13513816, 1.57969184, 1.47125058, 1.69520073],
        [1.70424357, 1.67294378, 1.99803467, 1.17655615, 1.3317925 ],
        [1.17505148, 1.0780165 , 1.6511064 , 1.08144937, 1.59447449]],

       [[1.91264682, 1.33161921, 1.17646838, 1.81680065, 1.93171856],
        [1.12086502, 1.72219922, 1.68680907, 1.47124441, 1.8869206 ],
        [1.28811097, 1.91661677, 1.97549623, 1.17347029, 1.61229793]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [120]:
# your code/answer here
print(a)
print(d)
#Relation: they both have the same shapes, in terms of values they are all floats
#Difference: array d is a incremented in 1



[[[0.13569819 0.13513816 0.57969184 0.47125058 0.69520073]
  [0.70424357 0.67294378 0.99803467 0.17655615 0.3317925 ]
  [0.17505148 0.0780165  0.6511064  0.08144937 0.59447449]]

 [[0.91264682 0.33161921 0.17646838 0.81680065 0.93171856]
  [0.12086502 0.72219922 0.68680907 0.47124441 0.8869206 ]
  [0.28811097 0.91661677 0.97549623 0.17347029 0.61229793]]]
[[[1.13569819 1.13513816 1.57969184 1.47125058 1.69520073]
  [1.70424357 1.67294378 1.99803467 1.17655615 1.3317925 ]
  [1.17505148 1.0780165  1.6511064  1.08144937 1.59447449]]

 [[1.91264682 1.33161921 1.17646838 1.81680065 1.93171856]
  [1.12086502 1.72219922 1.68680907 1.47124441 1.8869206 ]
  [1.28811097 1.91661677 1.97549623 1.17347029 1.61229793]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [121]:
# your code here
e = np.multiply(a,c)
e

array([[[0.13569819, 0.13513816, 0.57969184, 0.47125058, 0.69520073],
        [0.70424357, 0.67294378, 0.99803467, 0.17655615, 0.3317925 ],
        [0.17505148, 0.0780165 , 0.6511064 , 0.08144937, 0.59447449]],

       [[0.91264682, 0.33161921, 0.17646838, 0.81680065, 0.93171856],
        [0.12086502, 0.72219922, 0.68680907, 0.47124441, 0.8869206 ],
        [0.28811097, 0.91661677, 0.97549623, 0.17347029, 0.61229793]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [122]:
# your code/answer here
print(np.sum(a))
print(np.sum(e))
#Because we are multiplying "a" by an array of ones

15.5039325388903
15.5039325388903


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [123]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max)
print(d_min)
print(d_mean)


1.9980346661191586
1.0780165006534146
1.5167977512963433


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [124]:
# your code here
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [125]:
# your code here
for i in range(len(d)):
    for j in range(len(d[i])):

        for k in range(len(d[i][j])):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = 25
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] = 75
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 50
            elif d[i][j][k] == d_min:
                f[i][j][k] = 0
            elif d[i][j][k] == d_max:
                f[i][j][k] = 100
print(f)     
        

[[[ 25.  25.  75.  25.  75.]
  [ 75.  75. 100.  25.  25.]
  [ 25.   0.  75.  25.  75.]]

 [[ 75.  25.  25.  75.  75.]
  [ 25.  75.  75.  25.  75.]
  [ 25.  75.  75.  25.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [126]:
# your code here
#print(d)
print(f)


[[[ 25.  25.  75.  25.  75.]
  [ 75.  75. 100.  25.  25.]
  [ 25.   0.  75.  25.  75.]]

 [[ 75.  25.  25.  75.  75.]
  [ 25.  75.  75.  25.  75.]
  [ 25.  75.  75.  25.  75.]]]


int

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [128]:
# your code here
g = np.empty((2,3,5), dtype=str)
for i in range(len(d)):
    for j in range(len(d[i])):

        for k in range(len(d[i][j])):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                g[i][j][k] = 'A'
            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                g[i][j][k] = 'B'
            elif d[i][j][k] == d_mean:
                g[i][j][k] = 'C'
            elif d[i][j][k] == d_min:
                g[i][j][k] = 'D'
            elif d[i][j][k] == d_max:
                g[i][j][k] = 'E'
print(g)

[[['A' 'A' 'B' 'A' 'B']
  ['B' 'B' 'E' 'A' 'A']
  ['A' 'D' 'B' 'A' 'B']]

 [['B' 'A' 'A' 'B' 'B']
  ['A' 'B' 'B' 'A' 'B']
  ['A' 'B' 'B' 'A' 'B']]]
