# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [6]:
print (np.version.version)

1.18.1


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [20]:
a = np.random.randint(0, 10, (2,3,5))

In [21]:
a = np.random.random((2,3,5))

In [22]:
a = np.random.rand(2,3,5)

#### 4. Print *a*.


In [23]:
a

array([[[3, 8, 2, 6, 1],
        [0, 1, 5, 5, 8],
        [5, 4, 2, 2, 5]],

       [[0, 5, 7, 9, 5],
        [6, 8, 4, 3, 3],
        [3, 5, 8, 2, 7]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [43]:
b = np.ones((5,2,3), dtype='int32')

#### 6. Print *b*.


In [44]:
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [45]:
a.size == b.size

print(a.size)
print(b.size)

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [46]:
a+b
#We are not able because they have the same size but they don't have the same shape


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [50]:
#I have used reshape instead of transpose.
#With transpose, I don't get the same shape. I get (3,2,5) and not (2,3,5)


c = b.reshape((2,3,5))
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [54]:
d = a+c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [58]:
print (a)

print (d)

#What the sum does is to sum 1 in any item of the array

[[[3 8 2 6 1]
  [0 1 5 5 8]
  [5 4 2 2 5]]

 [[0 5 7 9 5]
  [6 8 4 3 3]
  [3 5 8 2 7]]]
[[[ 4  9  3  7  2]
  [ 1  2  6  6  9]
  [ 6  5  3  3  6]]

 [[ 1  6  8 10  6]
  [ 7  9  5  4  4]
  [ 4  6  9  3  8]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [59]:
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [63]:
e == a
#It is true because you are multiplying the original array per 1.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [66]:
d_max = d.max()
print(d_max)
d_min = d.min()
print(d_min)
d_mean = d.mean()
print(d_mean)

10
1
5.4


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [81]:
f = np.empty([2, 3, 5])
f

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [159]:
f = np.where(
    (d > d_min) & (d < d_mean), 25,
    np.where(
    (d > d_mean) & (d < d_max), 75,
    np.where(
    (d == d_mean), 50,
    np.where(
    (d == d_min), 0,
    np.where(
    (d == d_max), 100, 1000)))))
    

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [160]:
print(d)

print(f)

#I do have what I excepted

[[[ 4  9  3  7  2]
  [ 1  2  6  6  9]
  [ 6  5  3  3  6]]

 [[ 1  6  8 10  6]
  [ 7  9  5  4  4]
  [ 4  6  9  3  8]]]
[[[ 25  75  25  75  25]
  [  0  25  75  75  75]
  [ 75  25  25  25  75]]

 [[  0  75  75 100  75]
  [ 75  75  25  25  25]
  [ 25  75  75  25  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [158]:
g = np.where(
    (d > d_min) & (d < d_mean), 'B',
    np.where(
    (d > d_mean) & (d < d_max), 'D',
    np.where(
    (d == d_mean), 'C',
    np.where(
    (d == d_min), 'A',
    np.where(
    (d == d_max), 'E', 'X')))))
g

array([[['B', 'D', 'B', 'D', 'B'],
        ['A', 'B', 'D', 'D', 'D'],
        ['D', 'B', 'B', 'B', 'D']],

       [['A', 'D', 'D', 'E', 'D'],
        ['D', 'D', 'B', 'B', 'B'],
        ['B', 'D', 'D', 'B', 'D']]], dtype='<U1')